### ISSUE TITLE
Dosn't work and still looks like my code

### ISSUE THREAD

**Issue by Hardwaregore** [SirAlexBigBrain/RickRollerz#1]
@SirAlexBigBrain @SirAlexBigBrain @SirAlexBigBrain @SirAlexBigBrain @SirAlexBigBrain 

WHEN YOU COPY HOMEWORK, YOU MAKE IT LOOK LESS COPIED!!!! DO THE SAME THING HERE!!!!! I SUBMITTED A PULL REQUEST!!!! ACCEPT IT RIGHT NOW!!!!! STOP PIRATING MY CODE!!!!!

**Comment by TechDudie** [comment]
says the one who also pirated code hypocrite lol
